name: Start test run

on:
  schedule:
    - cron:  '00 21 * * 1-5'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload to browserstack and trigger tests
        run: |
         CONST=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ThePalaceProject/ios-binaries/commits)
         PAT=$(echo $CONST | jq -r '.[] | select(.commit.author.name=="runner")' | jq -r '.url')
         URL=${PAT:0:107}
         echo URL: $URL
         CONST2=$(curl -H "Accept: application/vnd.github.v3+json" $URL)
         readarray -t build_name <<<"$(jq '.files[].filename'<<<$CONST2)"
         PAT2=${build_name:1:19}
         unzip $PAT2
         BUILD_NAME = $PAT2
         file2=*.ipa
         echo file: $file2
         file2_abs_path=$(realpath $file2)
         APP_UPLOAD_RESPONSE=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }}" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@$file2_abs_path")
         APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
         echo APP_ID: $APP_ID
         echo "Triggering autotests"
         curl -X POST -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/ThePalaceProject/mobile-integration-tests/actions/workflows/maven.yml/dispatches -d '{"ref":"main", "inputs":{"test_tag":"(@tier1 or @tier2 or @tier3)","build_name":"'"$BUILD_NAME"'","bs_app_link":"'"$APP_ID"'","platform_name":"ios"}}' -H "Authorization: token ${{secrets.PERSONAL_TOKEN}}" 
      
