name: Smoke tests on iPhone 14 Pro Max 16

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
              
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

    
      - name: Debug Disk Space
        run: |
          df -h
          du -h --max-depth=1
