name: Smoke tests on iPhone 14 Pro Max 16

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Архивируем содержимое последнего коммита
      - name: Archive repository
        run: git archive --format=tar.gz -o latest_commit.tar.gz HEAD

      # Извлекаем архив
      - name: Extract archive
        run: tar -zxvf latest_commit.tar.gz

      # Отображаем текущее использование дискового пространства
      - name: Debug Disk Space
        run: |
          df -h
          du -h --max-depth=1
