name: Debug Workflow

on:
  push:
    branches:
      - master

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check System Information
        run: |
          uname -a
          df -h
          free -m
          cat /proc/cpuinfo
