name: Test run

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload to browserstack and trigger tests
        run:
         file = ${$GITHUB_WORKSPACE/Palace-1.0.3.14.zip}
         echo $file
