name: Test run

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload to browserstack and trigger tests
        run:
         ls $GITHUB_WORKSPACE/
         echo "hello"
